# Generated by Django 5.0.4 on 2024-05-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('oid', models.IntegerField(primary_key=True, serialize=False)),
                ('odate', models.DateTimeField(auto_now_add=True)),
                ('oname', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
